version: "3.8"
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - DRUPAL_DATABASE_PASSWORD=password123
      - DRUPAL_PASSWORD=admin
      - DRUPAL_USERNAME=user
    depends_on:
      - mariadb
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=bn_drupal
      - MARIADB_PASSWORD=password123
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - mariadb_data:/bitnami/mariadb
volumes:
  mariadb_data:
    driver: local
